# Generated by Django 5.1.7 on 2025-03-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('tags', models.TextField(blank=True, null=True)),
                ('published', models.CharField(max_length=255)),
                ('variant_sku', models.CharField(max_length=255)),
                ('variant_inventory_tracker', models.CharField(max_length=255)),
                ('variant_price', models.CharField(max_length=255)),
                ('image_src', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
