version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - django_network

#celery:
#    build: .
#    command: celery -A product_management worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#    networks:
#      - django_network


networks:
  django_network:
    driver: bridge

